/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type NavCategory = {
	_id: string;
	_type: 'navCategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
};

export type Series = {
	_id: string;
	_type: 'series';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	order?: number;
};

export type NavCategoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'navCategory';
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	navTitle?: string;
	order?: number;
	navCategory?: Array<
		{
			_key: string;
		} & NavCategoryReference
	>;
	body?: BlockContent;
	mainImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	secondaryImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type BlockContent = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
			}>;
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
			listItem?: 'bullet';
			markDefs?: Array<{
				href?: string;
				_type: 'link';
				_key: string;
			}>;
			level?: number;
			_type: 'block';
			_key: string;
	  }
	| {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
			_key: string;
	  }
>;

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type ImageType = {
	_id: string;
	_type: 'imageType';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	order?: number;
};

export type Event = {
	_id: string;
	_type: 'event';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	isMultiDay?: boolean;
	date?: string;
	startDate?: string;
	endDate?: string;
	time?: string;
	venueName?: string;
	venueAddress?: string;
	image?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	description?: BlockContent;
};

export type SeriesReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'series';
};

export type ImageTypeReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'imageType';
};

export type Artwork = {
	_id: string;
	_type: 'artwork';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderRank?: string;
	title?: string;
	slug?: Slug;
	size?: string;
	series?: Array<
		{
			_key: string;
		} & SeriesReference
	>;
	imgTypes?: Array<
		{
			_key: string;
		} & ImageTypeReference
	>;
	price?: number;
	sold?: boolean;
	etsyLink?: string;
	mainImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	originalDescription?: BlockContent;
	printsDescription?: BlockContent;
	commissionDescription?: BlockContent;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| NavCategory
	| Series
	| NavCategoryReference
	| SanityImageAssetReference
	| Page
	| SanityImageCrop
	| SanityImageHotspot
	| BlockContent
	| Slug
	| ImageType
	| Event
	| SeriesReference
	| ImageTypeReference
	| Artwork
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: ../web/src/routes/+layout.ts
// Variable: artistPagesQuery
// Query: *[_type == "page" && navCategory[0]->.title == "Meet the Artist"] | order(order asc){	_id,	title,	slug,	navTitle}
export type ArtistPagesQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	navTitle: string | null;
}>;

// Source: ../web/src/routes/+layout.ts
// Variable: artPagesQuery
// Query: *[_type == "page" && navCategory[0]->.title == "Experience Art"] | order(order asc){	_id,	title,	slug,	navTitle}
export type ArtPagesQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	navTitle: string | null;
}>;

// Source: ../web/src/routes/artist-biography/+page.ts
// Variable: bioQuery
// Query: *[_type == "page" && slug.current == 'artist-biography'] {	_id,	title,	slug,	body,	mainImage{		alt,		asset->{ url }	},	secondaryImage{		alt,		asset->{ url }	}}
export type BioQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	body: BlockContent | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
	secondaryImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/aspens/+page.ts
// Variable: aspensQuery
// Query: *[_type == "artwork" && ("Aspen" in series[]->title)] | order(orderRank) {	_id,	title,	slug,	size,	series[]->,	imgTypes[]->,	price,	sold,	originalDescription,	printsDescription,	commissionDescription,	etsyLink,	mainImage{		alt,		asset->{ url }	}}
export type AspensQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	size: string | null;
	series: Array<{
		_id: string;
		_type: 'series';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	imgTypes: Array<{
		_id: string;
		_type: 'imageType';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	price: number | null;
	sold: boolean | null;
	originalDescription: BlockContent | null;
	printsDescription: BlockContent | null;
	commissionDescription: BlockContent | null;
	etsyLink: string | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/colorado-flag/+page.ts
// Variable: coloradoFlagQuery
// Query: *[_type == "artwork" && ("Colorado Flag" in series[]->title)] | order(orderRank){	_id,	title,	slug,	size,	series[]->,	imgTypes[]->,	price,	sold,	originalDescription,	printsDescription,	commissionDescription,	etsyLink,	mainImage{		alt,		asset->{ url }	}}
export type ColoradoFlagQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	size: string | null;
	series: Array<{
		_id: string;
		_type: 'series';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	imgTypes: Array<{
		_id: string;
		_type: 'imageType';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	price: number | null;
	sold: boolean | null;
	originalDescription: BlockContent | null;
	printsDescription: BlockContent | null;
	commissionDescription: BlockContent | null;
	etsyLink: string | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/commissions/+page.ts
// Variable: commissionsQuery
// Query: *[_type == "artwork" && ("Commission" in imgTypes[]->title)] | order(orderRank){	_id,	title,	slug,	size,	series[0]->,	imgTypes[]->,	price,	sold,	originalDescription,	printsDescription,	commissionDescription,	etsyLink,	mainImage{		alt,		asset->{ url }	}}
export type CommissionsQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	size: string | null;
	series: {
		_id: string;
		_type: 'series';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	} | null;
	imgTypes: Array<{
		_id: string;
		_type: 'imageType';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	price: number | null;
	sold: boolean | null;
	originalDescription: BlockContent | null;
	printsDescription: BlockContent | null;
	commissionDescription: BlockContent | null;
	etsyLink: string | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/exhibitions/+page.ts
// Variable: eventsQuery
// Query: *[_type == "event" && (	(isMultiDay != true && date >= $today) ||	(isMultiDay == true && endDate >= $today))] | order(coalesce(startDate, date) asc) {	_id,	title,	isMultiDay,	date,	startDate,	endDate,	time,	venueName,	venueAddress,	description,	image {		alt,		asset->{ url }	}}
export type EventsQueryResult = Array<{
	_id: string;
	title: string | null;
	isMultiDay: boolean | null;
	date: string | null;
	startDate: string | null;
	endDate: string | null;
	time: string | null;
	venueName: string | null;
	venueAddress: string | null;
	description: BlockContent | null;
	image: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/fine-art-prints/+page.ts
// Variable: finePrintsQuery
// Query: *[_type == "artwork" && (title == "American War Horse" || title == "Blue Sky Basin" || title == "Moonlit Aspen")] | order(title asc){	_id,	title,	mainImage{		alt,		asset->{ url }	}}
export type FinePrintsQueryResult = Array<{
	_id: string;
	title: string | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/her-studio/+page.ts
// Variable: herStudioQuery
// Query: *[_type == "page" && slug.current == 'her-studio'] {	_id,	title,	slug,	body}
export type HerStudioQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	body: BlockContent | null;
}>;

// Source: ../web/src/routes/original-artwork/+page.ts
// Variable: originalArtworkQuery
// Query: *[_type == "artwork" && ("Original" in imgTypes[]->title)] | order(orderRank){	_id,	title,	slug,	size,	series[0]->,	imgTypes[]->,	price,	sold,	originalDescription,	printsDescription,	commissionDescription,	etsyLink,	mainImage{		alt,		asset->{ url }	}}
export type OriginalArtworkQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	size: string | null;
	series: {
		_id: string;
		_type: 'series';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	} | null;
	imgTypes: Array<{
		_id: string;
		_type: 'imageType';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	price: number | null;
	sold: boolean | null;
	originalDescription: BlockContent | null;
	printsDescription: BlockContent | null;
	commissionDescription: BlockContent | null;
	etsyLink: string | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Source: ../web/src/routes/other-artwork/+page.ts
// Variable: otherArtworkQuery
// Query: *[_type == "artwork" && ("Other" in series[]->title)] | order(orderRank){	_id,	title,	slug,	size,	series[]->,	imgTypes[]->,	price,	sold,	originalDescription,	printsDescription,	commissionDescription,	etsyLink,	mainImage{		alt,		asset->{ url }	}}
export type OtherArtworkQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	size: string | null;
	series: Array<{
		_id: string;
		_type: 'series';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	imgTypes: Array<{
		_id: string;
		_type: 'imageType';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		title?: string;
		order?: number;
	}> | null;
	price: number | null;
	sold: boolean | null;
	originalDescription: BlockContent | null;
	printsDescription: BlockContent | null;
	commissionDescription: BlockContent | null;
	etsyLink: string | null;
	mainImage: {
		alt: null;
		asset: {
			url: string | null;
		} | null;
	} | null;
}>;

// Query TypeMap
declare global {
	interface SanityQueries {
		'*[_type == "page" && navCategory[0]->.title == "Meet the Artist"] | order(order asc){\n\t_id,\n\ttitle,\n\tslug,\n\tnavTitle\n}': ArtistPagesQueryResult;
		'*[_type == "page" && navCategory[0]->.title == "Experience Art"] | order(order asc){\n\t_id,\n\ttitle,\n\tslug,\n\tnavTitle\n}': ArtPagesQueryResult;
		'*[_type == "page" && slug.current == \'artist-biography\'] {\n\t_id,\n\ttitle,\n\tslug,\n\tbody,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t},\n\tsecondaryImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': BioQueryResult;
		'*[_type == "artwork" && ("Aspen" in series[]->title)] | order(orderRank) {\n\t_id,\n\ttitle,\n\tslug,\n\tsize,\n\tseries[]->,\n\timgTypes[]->,\n\tprice,\n\tsold,\n\toriginalDescription,\n\tprintsDescription,\n\tcommissionDescription,\n\tetsyLink,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': AspensQueryResult;
		'*[_type == "artwork" && ("Colorado Flag" in series[]->title)] | order(orderRank){\n\t_id,\n\ttitle,\n\tslug,\n\tsize,\n\tseries[]->,\n\timgTypes[]->,\n\tprice,\n\tsold,\n\toriginalDescription,\n\tprintsDescription,\n\tcommissionDescription,\n\tetsyLink,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': ColoradoFlagQueryResult;
		'*[_type == "artwork" && ("Commission" in imgTypes[]->title)] | order(orderRank){\n\t_id,\n\ttitle,\n\tslug,\n\tsize,\n\tseries[0]->,\n\timgTypes[]->,\n\tprice,\n\tsold,\n\toriginalDescription,\n\tprintsDescription,\n\tcommissionDescription,\n\tetsyLink,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': CommissionsQueryResult;
		'*[_type == "event" && (\n\t(isMultiDay != true && date >= $today) ||\n\t(isMultiDay == true && endDate >= $today)\n)] | order(coalesce(startDate, date) asc) {\n\t_id,\n\ttitle,\n\tisMultiDay,\n\tdate,\n\tstartDate,\n\tendDate,\n\ttime,\n\tvenueName,\n\tvenueAddress,\n\tdescription,\n\timage {\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': EventsQueryResult;
		'*[_type == "artwork" && (title == "American War Horse" || title == "Blue Sky Basin" || title == "Moonlit Aspen")] | order(title asc){\n\t_id,\n\ttitle,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': FinePrintsQueryResult;
		'*[_type == "page" && slug.current == \'her-studio\'] {\n\t_id,\n\ttitle,\n\tslug,\n\tbody\n}': HerStudioQueryResult;
		'*[_type == "artwork" && ("Original" in imgTypes[]->title)] | order(orderRank){\n\t_id,\n\ttitle,\n\tslug,\n\tsize,\n\tseries[0]->,\n\timgTypes[]->,\n\tprice,\n\tsold,\n\toriginalDescription,\n\tprintsDescription,\n\tcommissionDescription,\n\tetsyLink,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': OriginalArtworkQueryResult;
		'*[_type == "artwork" && ("Other" in series[]->title)] | order(orderRank){\n\t_id,\n\ttitle,\n\tslug,\n\tsize,\n\tseries[]->,\n\timgTypes[]->,\n\tprice,\n\tsold,\n\toriginalDescription,\n\tprintsDescription,\n\tcommissionDescription,\n\tetsyLink,\n\tmainImage{\n\t\talt,\n\t\tasset->{ url }\n\t}\n}': OtherArtworkQueryResult;
	}
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
	interface SanityQueries extends globalThis.SanityQueries {}
}
